facebook:
  client:
    id: facebook
    clientId: 105703053274815
    clientSecret: 0e807dfd0dbb5177a1dab543232a3c01
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://graph.facebook.com/me
vk:
  client:
    id: vk
    clientId: 5831754
    clientSecret: wLFIdqtr4TRUDhLtNkHa
    accessTokenUri: https://oauth.vk.com/access_token
    userAuthorizationUri: https://oauth.vk.com/authorize
    tokenName: code
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://api.vk.com/method/users.get
google:
  client:
    id: google
    clientId: 916157345086-g2k288oqhj5lqundvjt946v36veas1im.apps.googleusercontent.com
    clientSecret: IJcwKwgXkD3r6xJkGQiaYhXa
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: profile email
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me